sudo: required
addons:
  sauce_connect: true
  firefox: latest
  chrome: stable
language: node_js
node_js:
- 8.9.4
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt install -y jq
script: npm test
branches:
  only:
  - master
  - develop
before_deploy:
  - build_version=$(cat package.json | jq '.version')
  - build_version=${build_version#\"}
  - build_version=${build_version%\"}
  - git tag -f v${build_version}
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $CHANGELOG_GITHUB_TOKEN
    file_glob: true
    file: dist/*
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: tjkpmonserrat@gmail.com
    api_key: $NPM_TOKEN
    on:
      branch: master
env:
  global:
  - secure: DDTOyeDL7krd+h7kdcxY62fI33f7j7e/z+Pe2rw3c5rNnV7Of5119BJoNzC01C/HCer9jo8xffpajmoBPaJ+deVf9jWGsNdRQ8NFtk1t8ikQTXk2RiMT6F28nkOY6weM+r9PYrdScn9OyUpSufutZ/qpHO8nRzZZxwMAb7oAeBHMTLbaa3EvL2dgYnzliLqIAFWNteiptlgz9ziFvsCxrKlPV4iJGRZNYtj/LdIVUPec77M1LrC7n+UcY24RzHx1FIcGIFcMoUzhLfgVINO97Gor8lraHMR+ixh20xhYpqLgDrPlqGDW0/fYsCh1Osu4ddujddsM0c8b+uB/jaTttq88k1AnDS4FhQE7uG5PWCMjbDpodT+EC/hRZ+blVVU0WkTUnd7OJjIcYX8w0KjRXRi4tZNEOsQx0q3G2Oy5dqyJ8UXyVW+vgu4nz3Ur8W2feSUXQfEBJENzSdsHvnOTIz1RebAeYARKn4JkOVPVDB9dcnDdfTDNJlZmi+JmlMDPdrWn7BuHbvwbfqMj7zQi2rG2DA/3maP1nG5ZWoRnEh8dAVihFjuKnfX3L6Lwmk7Vs7AosB1KA3PNbobKbQ8N0RUExi5qnwQP5eOuE2Zy5vy59QD5VUmNmNgoRGBFS0ej56GFhnca7CfEKmg4w12ptXYyN8IBkpkH8nT6XqC3vI8=
  - secure: pA1as/9lQOy9w5VnxwT60e4lks0d9ADsA6gXQE/wPsCUjHldQGTkfYVfG4KAdhF4ood6lgL3WgpRgumrprhQuTMp1mCySW3p32V4p1OEQmrLa7jhkGE0s6TGB0+FvEdMqAl+83GM70MdyNG1aT638G+x1PIV5bBsniZtYZdl4U+L7ywpqLzE2LtDGlVjnL7Hs1aiiDgDCZQk/fM7ULM4+VJYBCggIGyU0dll3VdclP+m8z4DxPeKE2LgQO1Px8OW/7HB7XTXblnh7AHxD/min6X6G8gzl8JD/AjDBiXG9CQ72pf3xIS/SzxyinsbbjkXiTVQUiBU9vGa9dxB7T2hsnckTPcqr13h9L6WT42qwEoqpH7+cvJRgMIeVy3DDpn+GrSoZwf0hgLIde/pHX44j6+Xsoh5ncBOIHNKBmHHRRCsRKr1D2vcGc8V93zEazw5BmpRp0e4faDeHI1ZJ9ZuwnTWflvdYj0PCIPDAAlclr+0jFj9POSms/zPo/X4WUJIerj8Ykpx9VWOzxRwli9DSbFEDwVC9V48GAqCWs7fXIaCvTdnjoMp9S4GLzyO7fKPyt84tihPFrRajN3T6/cJGyAzVkU1h9cKBPISOBclsaGN9lY8BUpK+GbO+MfSoHMF3c3Yx8z3/1Eok5vfhaU8SIyT06+2wservdAif+XAOqo=
